version: '3.8'

services:
  node-api:
    build: .
    container_name: hopeful_cohen
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AWS_COGNITO_APP_SUB: ${AWS_COGNITO_APP_SUB}
      AWS_COGNITO_RESOURCE_SEVER: ${AWS_COGNITO_RESOURCE_SEVER}
      AUTH_CHECK_STRING: ${AUTH_CHECK_STRING}
      MAILER_LITE_API_TOKEN: ${MAILER_LITE_API_TOKEN}
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
