version: '3.8'

services:
  node-api:
    build: .
    container_name: hopeful_cohen
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
