version: '3.8'

services:
  node-api-test:
    build:
      context: .
      dockerfile: Dockerfile.test  # Build using Dockerfile.test
    container_name: node-api-test
    environment:
      DATABASE_URL: ${DATABASE_URL}  # Make sure you define this environment variable
    networks:
      - app_network
    command: sh -c "bun run test; tail -f /dev/null"  # Run tests and keep the container running
    restart: no  # Avoid automatic restart of the container after completion
    stdin_open: true  # Keep the STDIN open
    tty: true  # Allocate a pseudo-TTY

networks:
  app_network:
    driver: bridge
