version: '3.8'

services:
  node-api:
    build: .
    container_name: hopeful_cohen
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_CHECK_STRING: ${AUTH_CHECK_STRING}
      MAILER_LITE_API_TOKEN: ${MAILER_LITE_API_TOKEN}
      AWS_COGNITO_REGION: ${AWS_COGNITO_REGION}
      AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID}
      AWS_COGNITO_CLIENT_ID: ${AWS_COGNITO_CLIENT_ID}
      AWS_USER_ACCESS_KEY: ${AWS_USER_ACCESS_KEY}
      AWS_USER_ACCESS_SECRET: ${AWS_USER_ACCESS_SECRET}
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
