name: CI/CD Pipeline for Node.js API and PostgreSQL
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from the repository
        uses: actions/checkout@v2

      - name: Set up SSH key for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" | base64 --decode > ~/.ssh/test-initial.pem
          chmod 600 ~/.ssh/test-initial.pem  # Set correct permissions for the key
          ls -l ~/.ssh  # Check permissions and verify file

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Add SSH Key to Agent
        run: |
          eval $(ssh-agent -s)  # Start the SSH agent
          ssh-add ~/.ssh/test-initial.pem  # Add the private key to the agent

      - name: SSH into EC2 and deploy
        run: |
          echo "Running SSH command..."
          set -x  # Enable shell debugging

          ssh -vvv -i ~/.ssh/test-initial.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@${{ secrets.AWS_EC2_HOST }} <<'EOF'
            echo "SSH connected to EC2 instance"
            
            # Navigate to the project directory
            cd /home/ec2-user/node-test || exit
            ls -l

            # Export secrets as environment variables
            export POSTGRES_USER=${{ secrets.AWS_POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.AWS_POSTGRES_PASSWORD }}
            export POSTGRES_DB=${{ secrets.AWS_POSTGRES_DB }}
            export DATABASE_URL=${{ secrets.AWS_DATABASE_URL }}

            # Step 1: Ensure Docker is installed on EC2
            if ! command -v docker &> /dev/null; then
                echo "Docker is not installed. Installing Docker..."
                sudo apt-get update
                sudo apt-get install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
            else
                echo "Docker is already installed."
            fi

            # Step 2: Ensure Docker Compose is installed
            if ! command -v docker-compose &> /dev/null; then
                echo "Docker Compose is not installed. Installing Docker Compose..."
                sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            else
                echo "Docker Compose is already installed."
            fi

            # Step 3: Pull the latest code from GitHub
            echo "Pulling latest code from GitHub"
            git fetch origin
            git checkout master
            git pull origin master

            # Step 4: Run tests using docker-compose.test.yml (without --abort-on-container-exit)
            echo "Running tests using docker-compose.test.yml"
            docker-compose -f docker-compose.test.yml up -d  # Run tests without aborting other containers

            # Get the container ID of the test container
            TEST_CONTAINER_ID=$(docker ps -q --filter "name=node-api-test")

            if [ -z "$TEST_CONTAINER_ID" ]; then
                echo "Test container not found, stopping deployment."
                exit 1  # Stop deployment if test container is not found
            fi

            # Get the exit code of the test container
              TEST_EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' "$TEST_CONTAINER_ID")
              echo "Test container exit code: $TEST_EXIT_CODE"

              if [ "$TEST_EXIT_CODE" -eq 0 ]; then
                  echo "Tests passed, proceeding with deployment."
              else
                  echo "Tests failed, stopping deployment."
                  docker-compose -f docker-compose.test.yml down  # Clean up containers
                  exit 1  # Stop deployment if tests failed
              fi

            # Cleanup: Stop and remove the test container
            echo "Cleaning up test container..."
            docker-compose -f docker-compose.test.yml down

            # Step 5: Run production containers using docker-compose.yml
            echo "Running docker-compose up for production containers"
            docker-compose up -d  # Start production containers (Postgres, Node.js app)

            # Wait for the Node.js app container to be fully started
            echo "Waiting for Node.js app container to start..."
            sleep 10  # Give the container time to initialize

            # Run Prisma migrations inside the production container
            echo "Running Prisma migrations..."
            docker-compose exec node-api bun prisma migrate deploy

            echo "Deployment completed."
          EOF
